### ISSUE TITLE
What is the use of projection layer

### ISSUE THREAD

**Issue by nikhilrayaprolu** [iesl/dilated-cnn-ner#14]
https://github.com/iesl/dilated-cnn-ner/blob/master/src/cnn.py#L252
There is a projection layer that is mentioned in the code what is the advantage found by using the projection layer.
I couldn't find any experimental evidence being mentioned in the paper.

**Comment by strubell** [comment]
In initial experiments we didn't find the projection layer to help, so we didn't use it in the results presented in the paper.
