### ISSUE TITLE
Questions regarding differences between the implementation and the experiment details in the research paper

### ISSUE THREAD

**Issue by nikhilrayaprolu** [iesl/dilated-cnn-ner#15]
Are configuration files similar to the Paper?
https://github.com/iesl/dilated-cnn-ner/blob/master/conf/ontonotes/dilated-cnn.conf
I find that number of the convolutional layers in the configuration files is 3 but the paper has mentioned that each block contains 4 layers. So are these configuration files aren't similar to the ones used in the paper?

Secondly, I find an extra convolution layer for initial projection used in this implementation, what is the significance of the extra convolutional layer? I find that nothing of such is mentioned in the research paper.

**Comment by strubell** [comment]
Yes, the configuration files should implement the same models reported in the paper.

I think you've answered your own question: the 4 layers for the sentence-level dilated CNN model are the 3 layers defined in the `layers` json, plus the initial projection.

**Comment by nikhilrayaprolu** [comment]
Okay so does this mean, there is nowhere in the experiments where a dilation rate of 4 is used? Then does that affect the total receptive field of the CNN? since using a dilation of 2 doesn't give us a good level of receptive field(effective input width as per the paper).

**Comment by nikhilrayaprolu** [comment]
I am planning to make a pytorch equivalent of the research paper, and try few extensions for it. Thank You, for your quick replies. your quick replies would surely help me do it better and quicker.

**Comment by strubell** [comment]
Great, let me know if you have further questions!
