### ISSUE TITLE
Training issue

### ISSUE THREAD

**Issue by xain123** [iesl/dilated-cnn-ner#19]
![image](https://user-images.githubusercontent.com/32290104/40480926-53a41fa4-5f69-11e8-93c8-b994ee453233.png)

i am face this error while training. any solution?

**Comment by strubell** [comment]
sorry for not seeing this sooner, but this is due to using a newer version of tensorflow than the code supports. You need to use a version earlier than 1.4. I've changed the readme accordingly.
