### ISSUE TITLE
Did you try your model on other seq labeling tasks like Chunking or POS?

### ISSUE THREAD

**Issue by PengLU1101** [iesl/dilated-cnn-ner#21]
Hi, I am doing some work on seq labeling task.

Being curious about the results of your model on such kind of datasets, like Chunking and POS.

**Comment by strubell** [comment]
No, I never tried it -- I would guess it would work well for POS since that
doesn't require much context anyway, and I would be interested to know how
it does on chunking! Should be easy to get e.g. the conll chunking dataset
into the same format as this code requires.
