### ISSUE TITLE
Getting some issue with permission beyond my understanding

### ISSUE THREAD

**Issue by Surojit88** [iesl/dilated-cnn-ner#23]
Hello,

I have replicated the git directory structure as provided here and I ran the following:

(This has the bin, conf, and src folders with the relevant files)
`export DILATED_CNN_NER_ROOT=`/home/ss06886910/NLP/Bilstm_Dilated_CNN_NER``

(This has the english corpus in the form of train.txt test.txt and valid.txt)
train.txt excerpt:

> -DOCSTART- -X- -X- O
> 
> EU NNP B-NP B-ORG
> rejects VBZ B-VP O
> German JJ B-NP B-MISC
> call NN I-NP O
> to TO B-VP O
> boycott VB I-VP O
> British JJ B-NP B-MISC
> lamb NN I-NP O
> . . O O
> 
> Peter NNP B-NP B-PER
> Blackburn NNP I-NP I-PER
> 
> BRUSSELS NNP B-NP B-LOC
> 1996-08-22 CD I-NP O

`export DATA_DIR='/home/ss06886910/NLP/Bilstm_Dilated_CNN_NER/data/conll2003
`

Upon running the following command:
`./bin/preprocess.sh conf/conll/dilated-cnn.conf`
; I am getting a bunch of permission denied errors which, am unable to fathom why. Am sorry if the question is very lame but, can anyone help me here?

Tried redirecting the trace to a text file which could only capture this:

> "Writing extra vocab (cutoff ) to "

Trace thrown at terminal:

find: ‘/proc/4416/map_files’: Permission denied
find: ‘/proc/4416/fdinfo’: Permission denied
find: ‘/proc/4416/ns’: Permission denied
find: ‘/proc/4430/task/4430/fd’: Permission denied
find: ‘/proc/4430/task/4430/fdinfo’: Permission denied
find: ‘/proc/4430/task/4430/ns’: Permission denied
find: ‘/proc/4430/task/4438/fd’: Permission denied
find: ‘/proc/4430/task/4438/fdinfo’: Permission denied
find: ‘/proc/4430/task/4438/ns’: Permission denied
find: ‘/proc/4430/task/4439/fd’: Permission denied
find: ‘/proc/4430/task/4439/fdinfo’: Permission denied
find: ‘/proc/4430/task/4439/ns’: Permission denied
find: ‘/proc/4430/task/4440/fd’: Permission denied
find: ‘/proc/4430/task/4440/fdinfo’: Permission denied
find: ‘/proc/4430/task/4440/ns’: Permission denied
find: ‘/proc/4430/task/4441/fd’: Permission denied
find: ‘/proc/4430/task/4441/fdinfo’: Permission denied
find: ‘/proc/4430/task/4441/ns’: Permission denied
find: ‘/proc/4430/task/4442/fd’: Permission denied
find: ‘/proc/4430/task/4442/fdinfo’: Permission denied
find: ‘/proc/4430/task/4442/ns’: Permission denied
find: ‘/proc/4430/task/4443/fd’: Permission denied
find: ‘/proc/4430/task/4443/fdinfo’: Permission denied
find: ‘/proc/4430/task/4443/ns’: Permission denied
find: ‘/proc/4430/task/4444/fd’: Permission denied
find: ‘/proc/4430/task/4444/fdinfo’: Permission denied
find: ‘/proc/4430/task/4444/ns’: Permission denied
find: ‘/proc/4430/task/4445/fd’: Permission denied
find: ‘/proc/4430/task/4445/fdinfo’: Permission denied
find: ‘/proc/4430/task/4445/ns’: Permission denied
find: ‘/proc/4430/task/4542/fd’: Permission denied
find: ‘/proc/4430/task/4542/fdinfo’: Permission denied
find: ‘/proc/4430/task/4542/ns’: Permission denied
find: ‘/proc/4430/task/4543/fd’: Permission denied
find: ‘/proc/4430/task/4543/fdinfo’: Permission denied
find: ‘/proc/4430/task/4543/ns’: Permission denied
find: ‘/proc/4430/task/4544/fd’: Permission denied
find: ‘/proc/4430/task/4544/fdinfo’: Permission denied
find: ‘/proc/4430/task/4544/ns’: Permission denied
find: ‘/proc/4430/task/4545/fd’: Permission denied
find: ‘/proc/4430/task/4545/fdinfo’: Permission denied
find: ‘/proc/4430/task/4545/ns’: Permission denied
find: ‘/proc/4430/task/4546/fd’: Permission denied
find: ‘/proc/4430/task/4546/fdinfo’: Permission denied
find: ‘/proc/4430/task/4546/ns’: Permission denied
find: ‘/proc/4430/task/4547/fd’: Permission denied
find: ‘/proc/4430/task/4547/fdinfo’: Permission denied
find: ‘/proc/4430/task/4547/ns’: Permission denied
find: ‘/proc/4430/task/4548/fd’: Permission denied
find: ‘/proc/4430/task/4548/fdinfo’: Permission denied
find: ‘/proc/4430/task/4548/ns’: Permission denied
find: ‘/proc/4430/task/4549/fd’: Permission denied
find: ‘/proc/4430/task/4549/fdinfo’: Permission denied
find: ‘/proc/4430/task/4549/ns’: Permission denied
find: ‘/proc/4430/task/4550/fd’: Permission denied
find: ‘/proc/4430/task/4550/fdinfo’: Permission denied
find: ‘/proc/4430/task/4550/ns’: Permission denied
find: ‘/proc/4430/task/4551/fd’: Permission denied
find: ‘/proc/4430/task/4551/fdinfo’: Permission denied
find: ‘/proc/4430/task/4551/ns’: Permission denied
find: ‘/proc/4430/task/4552/fd’: Permission denied
find: ‘/proc/4430/task/4552/fdinfo’: Permission denied
find: ‘/proc/4430/task/4552/ns’: Permission denied
find: ‘/proc/4430/fd’: Permission denied
find: ‘/proc/4430/map_files’: Permission denied
find: ‘/proc/4430/fdinfo’: Permission denied
find: ‘/proc/4430/ns’: Permission denied
find: ‘/proc/5253/task/5253/fd’: Permission denied
find: ‘/proc/5253/task/5253/fdinfo’: Permission denied
find: ‘/proc/5253/task/5253/ns’: Permission denied
find: ‘/proc/5253/fd’: Permission denied
find: ‘/proc/5253/map_files’: Permission denied
find: ‘/proc/5253/fdinfo’: Permission denied
find: ‘/proc/5253/ns’: Permission denied
find: ‘/proc/5263/task/5263/fd’: Permission denied
find: ‘/proc/5263/task/5263/fdinfo’: Permission denied
find: ‘/proc/5263/task/5263/ns’: Permission denied
find: ‘/proc/5263/fd’: Permission denied
find: ‘/proc/5263/map_files’: Permission denied
find: ‘/proc/5263/fdinfo’: Permission denied
find: ‘/proc/5263/ns’: Permission denied
find: ‘/proc/5751/task/5751/fd’: Permission denied
find: ‘/proc/5751/task/5751/fdinfo’: Permission denied
find: ‘/proc/5751/task/5751/ns’: Permission denied
find: ‘/proc/5751/task/5756/fd’: Permission denied
find: ‘/proc/5751/task/5756/fdinfo’: Permission denied
find: ‘/proc/5751/task/5756/ns’: Permission denied
find: ‘/proc/5751/task/5757/fd’: Permission denied
find: ‘/proc/5751/task/5757/fdinfo’: Permission denied
find: ‘/proc/5751/task/5757/ns’: Permission denied
find: ‘/proc/5751/task/5758/fd’: Permission denied
find: ‘/proc/5751/task/5758/fdinfo’: Permission denied
find: ‘/proc/5751/task/5758/ns’: Permission denied
find: ‘/proc/5751/task/5759/fd’: Permission denied
find: ‘/proc/5751/task/5759/fdinfo’: Permission denied
find: ‘/proc/5751/task/5759/ns’: Permission denied
find: ‘/proc/5751/task/5760/fd’: Permission denied
find: ‘/proc/5751/task/5760/fdinfo’: Permission denied
find: ‘/proc/5751/task/5760/ns’: Permission denied
find: ‘/proc/5751/task/5761/fd’: Permission denied
find: ‘/proc/5751/task/5761/fdinfo’: Permission denied
find: ‘/proc/5751/task/5761/ns’: Permission denied
find: ‘/proc/5751/task/5762/fd’: Permission denied
find: ‘/proc/5751/task/5762/fdinfo’: Permission denied
find: ‘/proc/5751/task/5762/ns’: Permission denied
find: ‘/proc/5751/task/5763/fd’: Permission denied
find: ‘/proc/5751/task/5763/fdinfo’: Permission denied
find: ‘/proc/5751/task/5763/ns’: Permission denied
find: ‘/proc/5751/fd’: Permission denied
find: ‘/proc/5751/map_files’: Permission denied
find: ‘/proc/5751/fdinfo’: Permission denied
find: ‘/proc/5751/ns’: Permission denied
find: ‘/proc/6305/task/6305/fd’: Permission denied
find: ‘/proc/6305/task/6305/fdinfo’: Permission denied
find: ‘/proc/6305/task/6305/ns’: Permission denied
find: ‘/proc/6305/fd’: Permission denied
find: ‘/proc/6305/map_files’: Permission denied
find: ‘/proc/6305/fdinfo’: Permission denied
find: ‘/proc/6305/ns’: Permission denied
find: ‘/proc/8210/task/8210/fd’: Permission denied
find: ‘/proc/8210/task/8210/fdinfo’: Permission denied
find: ‘/proc/8210/task/8210/ns’: Permission denied
find: ‘/proc/8210/fd’: Permission denied
find: ‘/proc/8210/map_files’: Permission denied
find: ‘/proc/8210/fdinfo’: Permission denied
find: ‘/proc/8210/ns’: Permission denied
find: ‘/proc/10926/task/10926/fd’: Permission denied
find: ‘/proc/10926/task/10926/fdinfo’: Permission denied
find: ‘/proc/10926/task/10926/ns’: Permission denied
find: ‘/proc/10926/task/10931/fd’: Permission denied
find: ‘/proc/10926/task/10931/fdinfo’: Permission denied
find: ‘/proc/10926/task/10931/ns’: Permission denied
find: ‘/proc/10926/task/10932/fd’: Permission denied
find: ‘/proc/10926/task/10932/fdinfo’: Permission denied
find: ‘/proc/10926/task/10932/ns’: Permission denied
find: ‘/proc/10926/task/10933/fd’: Permission denied
find: ‘/proc/10926/task/10933/fdinfo’: Permission denied
find: ‘/proc/10926/task/10933/ns’: Permission denied
find: ‘/proc/10926/task/10934/fd’: Permission denied
find: ‘/proc/10926/task/10934/fdinfo’: Permission denied
find: ‘/proc/10926/task/10934/ns’: Permission denied
find: ‘/proc/10926/task/10935/fd’: Permission denied
find: ‘/proc/10926/task/10935/fdinfo’: Permission denied
find: ‘/proc/10926/task/10935/ns’: Permission denied
find: ‘/proc/10926/task/10936/fd’: Permission denied
find: ‘/proc/10926/task/10936/fdinfo’: Permission denied
find: ‘/proc/10926/task/10936/ns’: Permission denied
find: ‘/proc/10926/task/10937/fd’: Permission denied
find: ‘/proc/10926/task/10937/fdinfo’: Permission denied
find: ‘/proc/10926/task/10937/ns’: Permission denied
find: ‘/proc/10926/task/10938/fd’: Permission denied
find: ‘/proc/10926/task/10938/fdinfo’: Permission denied
find: ‘/proc/10926/task/10938/ns’: Permission denied
find: ‘/proc/10926/task/11251/fd’: Permission denied
find: ‘/proc/10926/task/11251/fdinfo’: Permission denied
find: ‘/proc/10926/task/11251/ns’: Permission denied
find: ‘/proc/10926/task/11252/fd’: Permission denied
find: ‘/proc/10926/task/11252/fdinfo’: Permission denied
find: ‘/proc/10926/task/11252/ns’: Permission denied
find: ‘/proc/10926/task/11253/fd’: Permission denied
find: ‘/proc/10926/task/11253/fdinfo’: Permission denied
find: ‘/proc/10926/task/11253/ns’: Permission denied
find: ‘/proc/10926/task/11254/fd’: Permission denied
find: ‘/proc/10926/task/11254/fdinfo’: Permission denied
find: ‘/proc/10926/task/11254/ns’: Permission denied
find: ‘/proc/10926/task/11255/fd’: Permission denied
find: ‘/proc/10926/task/11255/fdinfo’: Permission denied
find: ‘/proc/10926/task/11255/ns’: Permission denied
find: ‘/proc/10926/task/11256/fd’: Permission denied
find: ‘/proc/10926/task/11256/fdinfo’: Permission denied
find: ‘/proc/10926/task/11256/ns’: Permission denied
find: ‘/proc/10926/task/11257/fd’: Permission denied
find: ‘/proc/10926/task/11257/fdinfo’: Permission denied
find: ‘/proc/10926/task/11257/ns’: Permission denied
find: ‘/proc/10926/task/11258/fd’: Permission denied
find: ‘/proc/10926/task/11258/fdinfo’: Permission denied
find: ‘/proc/10926/task/11258/ns’: Permission denied
find: ‘/proc/10926/task/11259/fd’: Permission denied
find: ‘/proc/10926/task/11259/fdinfo’: Permission denied
find: ‘/proc/10926/task/11259/ns’: Permission denied
find: ‘/proc/10926/task/11260/fd’: Permission denied
find: ‘/proc/10926/task/11260/fdinfo’: Permission denied
find: ‘/proc/10926/task/11260/ns’: Permission denied
find: ‘/proc/10926/task/11261/fd’: Permission denied
find: ‘/proc/10926/task/11261/fdinfo’: Permission denied
find: ‘/proc/10926/task/11261/ns’: Permission denied
find: ‘/proc/10926/fd’: Permission denied
find: ‘/proc/10926/map_files’: Permission denied
find: ‘/proc/10926/fdinfo’: Permission denied
find: ‘/proc/10926/ns’: Permission denied
find: ‘/proc/10940/task/10940/fd’: Permission denied
find: ‘/proc/10940/task/10940/fdinfo’: Permission denied
find: ‘/proc/10940/task/10940/ns’: Permission denied
find: ‘/proc/10940/fd’: Permission denied
find: ‘/proc/10940/map_files’: Permission denied
find: ‘/proc/10940/fdinfo’: Permission denied
find: ‘/proc/10940/ns’: Permission denied
find: ‘/proc/12186/task/12186/fd’: Permission denied
find: ‘/proc/12186/task/12186/fdinfo’: Permission denied
find: ‘/proc/12186/task/12186/ns’: Permission denied
find: ‘/proc/12186/task/12192/fd’: Permission denied
find: ‘/proc/12186/task/12192/fdinfo’: Permission denied
find: ‘/proc/12186/task/12192/ns’: Permission denied
find: ‘/proc/12186/task/12193/fd’: Permission denied
find: ‘/proc/12186/task/12193/fdinfo’: Permission denied
find: ‘/proc/12186/task/12193/ns’: Permission denied
find: ‘/proc/12186/task/12194/fd’: Permission denied
find: ‘/proc/12186/task/12194/fdinfo’: Permission denied
find: ‘/proc/12186/task/12194/ns’: Permission denied
find: ‘/proc/12186/task/12195/fd’: Permission denied
find: ‘/proc/12186/task/12195/fdinfo’: Permission denied
find: ‘/proc/12186/task/12195/ns’: Permission denied
find: ‘/proc/12186/task/12196/fd’: Permission denied
find: ‘/proc/12186/task/12196/fdinfo’: Permission denied
find: ‘/proc/12186/task/12196/ns’: Permission denied
find: ‘/proc/12186/task/12197/fd’: Permission denied
find: ‘/proc/12186/task/12197/fdinfo’: Permission denied
find: ‘/proc/12186/task/12197/ns’: Permission denied
find: ‘/proc/12186/task/12198/fd’: Permission denied
find: ‘/proc/12186/task/12198/fdinfo’: Permission denied
find: ‘/proc/12186/task/12198/ns’: Permission denied
find: ‘/proc/12186/task/12199/fd’: Permission denied
find: ‘/proc/12186/task/12199/fdinfo’: Permission denied
find: ‘/proc/12186/task/12199/ns’: Permission denied
find: ‘/proc/12186/fd’: Permission denied
find: ‘/proc/12186/map_files’: Permission denied
find: ‘/proc/12186/fdinfo’: Permission denied
find: ‘/proc/12186/ns’: Permission denied
find: ‘/proc/12213/task/12213/fd’: Permission denied
find: ‘/proc/12213/task/12213/fdinfo’: Permission denied
find: ‘/proc/12213/task/12213/ns’: Permission denied
find: ‘/proc/12213/fd’: Permission denied
find: ‘/proc/12213/map_files’: Permission denied
find: ‘/proc/12213/fdinfo’: Permission denied
find: ‘/proc/12213/ns’: Permission denied
find: ‘/proc/13454/task/13454/fd’: Permission denied
find: ‘/proc/13454/task/13454/fdinfo’: Permission denied
find: ‘/proc/13454/task/13454/ns’: Permission denied
find: ‘/proc/13454/fd’: Permission denied
find: ‘/proc/13454/map_files’: Permission denied
find: ‘/proc/13454/fdinfo’: Permission denied
find: ‘/proc/13454/ns’: Permission denied
find: ‘/proc/14018/task/14018/fd’: Permission denied
find: ‘/proc/14018/task/14018/fdinfo’: Permission denied
find: ‘/proc/14018/task/14018/ns’: Permission denied
find: ‘/proc/14018/fd’: Permission denied
find: ‘/proc/14018/map_files’: Permission denied
find: ‘/proc/14018/fdinfo’: Permission denied
find: ‘/proc/14018/ns’: Permission denied
find: ‘/proc/14207/task/14207/fd’: Permission denied
find: ‘/proc/14207/task/14207/fdinfo’: Permission denied
find: ‘/proc/14207/task/14207/ns’: Permission denied
find: ‘/proc/14207/fd’: Permission denied
find: ‘/proc/14207/map_files’: Permission denied
find: ‘/proc/14207/fdinfo’: Permission denied
find: ‘/proc/14207/ns’: Permission denied
find: ‘/proc/14383/task/14383/fd’: Permission denied
find: ‘/proc/14383/task/14383/fdinfo’: Permission denied
find: ‘/proc/14383/task/14383/ns’: Permission denied
find: ‘/proc/14383/fd’: Permission denied
find: ‘/proc/14383/map_files’: Permission denied
find: ‘/proc/14383/fdinfo’: Permission denied
find: ‘/proc/14383/ns’: Permission denied
find: ‘/proc/15976/task/15976/fd’: Permission denied
find: ‘/proc/15976/task/15976/fdinfo’: Permission denied
find: ‘/proc/15976/task/15976/ns’: Permission denied
find: ‘/proc/15976/fd’: Permission denied
find: ‘/proc/15976/map_files’: Permission denied
find: ‘/proc/15976/fdinfo’: Permission denied
find: ‘/proc/15976/ns’: Permission denied
find: ‘/proc/17376’: No such file or directory
find: ‘/proc/17377’: No such file or directory
find: ‘/proc/17378’: No such file or directory
find: ‘/proc/17379’: No such file or directory
find: ‘/proc/17380’: No such file or directory
find: ‘/proc/17381’: No such file or directory
find: ‘/proc/17382’: No such file or directory
find: ‘/proc/17383’: No such file or directory
find: ‘/proc/17384’: No such file or directory
find: ‘/proc/17385’: No such file or directory
find: ‘/proc/17386’: No such file or directory
find: ‘/proc/17387’: No such file or directory
find: ‘/proc/17432/task/17432/fd’: Permission denied
find: ‘/proc/17432/task/17432/fdinfo’: Permission denied
find: ‘/proc/17432/task/17432/ns’: Permission denied
find: ‘/proc/17432/fd’: Permission denied
find: ‘/proc/17432/map_files’: Permission denied
find: ‘/proc/17432/fdinfo’: Permission denied
find: ‘/proc/17432/ns’: Permission denied
find: ‘/run/firewalld’: Permission denied
find: ‘/run/chrony’: Permission denied
find: ‘/run/user/0’: Permission denied
find: ‘/run/setroubleshoot’: Permission denied
find: ‘/run/cups/certs’: Permission denied
find: ‘/run/screen/S-root’: Permission denied
find: ‘/run/sudo’: Permission denied
find: ‘/run/svnserve’: Permission denied
find: ‘/run/mdadm’: Permission denied
find: ‘/run/rpcbind’: Permission denied
find: ‘/run/lvm’: Permission denied
find: ‘/run/log/journal/3dc67f142b1944bbbf7ce95ef99eaecf’: Permission denied
find: ‘/run/lock/iscsi’: Permission denied
find: ‘/run/lock/lvm’: Permission denied
find: ‘/run/systemd/inaccessible’: Permission denied
find: ‘/sys/kernel/debug’: Permission denied
find: ‘/etc/grub.d’: Permission denied
find: ‘/etc/pki/CA/private’: Permission denied
find: ‘/etc/pki/rsyslog’: Permission denied
find: ‘/etc/lvm/archive’: Permission denied
find: ‘/etc/lvm/backup’: Permission denied
find: ‘/etc/lvm/cache’: Permission denied
find: ‘/etc/dhcp’: Permission denied
find: ‘/etc/polkit-1/rules.d’: Permission denied
find: ‘/etc/polkit-1/localauthority’: Permission denied
find: ‘/etc/selinux/targeted/active’: Permission denied
find: ‘/etc/selinux/targeted/tmp’: Permission denied
find: ‘/etc/selinux/final’: Permission denied
find: ‘/etc/ntp/crypto’: Permission denied
find: ‘/etc/cups/ssl’: Permission denied
find: ‘/etc/firewalld’: Permission denied
find: ‘/etc/audisp’: Permission denied
find: ‘/etc/audit’: Permission denied
find: ‘/etc/sudoers.d’: Permission denied
find: ‘/etc/sssd’: Permission denied
find: ‘/etc/ipsec.d’: Permission denied
find: ‘/etc/libvirt’: Permission denied
find: ‘/etc/vmware-tools/GuestProxyData/trusted’: Permission denied
find: ‘/root’: Permission denied
find: ‘/var/tmp/yum-root-0UCJ73’: Permission denied
find: ‘/var/tmp/systemd-private-367606d032b940299d5c2644ad90e90a-chronyd.service-8RBMyl’: Permission denied
find: ‘/var/tmp/systemd-private-367606d032b940299d5c2644ad90e90a-cups.service-hdJOPc’: Permission denied
find: ‘/var/lib/yum/history/2018-09-12/1’: Permission denied
find: ‘/var/lib/yum/history/2018-09-12/2’: Permission denied
find: ‘/var/lib/yum/history/2018-09-12/3’: Permission denied
find: ‘/var/lib/yum/history/2018-09-12/4’: Permission denied
find: ‘/var/lib/yum/history/2018-09-12/5’: Permission denied
find: ‘/var/lib/yum/history/2018-09-12/6’: Permission denied
find: ‘/var/lib/yum/history/2018-09-12/7’: Permission denied
find: ‘/var/lib/yum/history/2018-09-12/8’: Permission denied
find: ‘/var/lib/yum/history/2018-09-12/9’: Permission denied
find: ‘/var/lib/yum/history/2018-09-12/10’: Permission denied
find: ‘/var/lib/yum/history/2018-09-12/11’: Permission denied
find: ‘/var/lib/yum/history/2018-09-12/12’: Permission denied
find: ‘/var/lib/yum/history/2018-09-12/13’: Permission denied
find: ‘/var/lib/yum/history/2018-09-12/14’: Permission denied
find: ‘/var/lib/yum/history/2018-09-12/15’: Permission denied
find: ‘/var/lib/yum/history/2018-09-12/16’: Permission denied
find: ‘/var/lib/yum/history/2018-09-12/17’: Permission denied
find: ‘/var/lib/yum/history/2018-09-12/18’: Permission denied
find: ‘/var/lib/yum/history/2018-09-12/19’: Permission denied
find: ‘/var/lib/yum/history/2018-09-12/20’: Permission denied
find: ‘/var/lib/yum/history/2018-09-12/21’: Permission denied
find: ‘/var/lib/yum/history/2018-09-12/22’: Permission denied
find: ‘/var/lib/machines’: Permission denied
find: ‘/var/lib/polkit-1’: Permission denied
find: ‘/var/lib/NetworkManager’: Permission denied
find: ‘/var/lib/postfix’: Permission denied
find: ‘/var/lib/rsyslog’: Permission denied
find: ‘/var/lib/authconfig’: Permission denied
find: ‘/var/lib/samba/private’: Permission denied
find: ‘/var/lib/rpcbind’: Permission denied
find: ‘/var/lib/certmonger/cas’: Permission denied
find: ‘/var/lib/certmonger/local’: Permission denied
find: ‘/var/lib/certmonger/requests’: Permission denied
find: ‘/var/lib/tpm’: Permission denied
find: ‘/var/lib/libvirt/boot’: Permission denied
find: ‘/var/lib/libvirt/filesystems’: Permission denied
find: ‘/var/lib/libvirt/images’: Permission denied
find: ‘/var/lib/libvirt/network’: Permission denied
find: ‘/var/lib/libvirt/qemu’: Permission denied
find: ‘/var/lib/pulse’: Permission denied
find: ‘/var/lib/gdm’: Permission denied
find: ‘/var/lib/setroubleshoot’: Permission denied
find: ‘/var/lib/gssproxy/clients’: Permission denied
find: ‘/var/lib/gssproxy/rcache’: Permission denied
find: ‘/var/lib/nfs/statd’: Permission denied
find: ‘/var/lib/udisks2’: Permission denied
find: ‘/var/lib/sss/db’: Permission denied
find: ‘/var/lib/sss/pipes/private’: Permission denied
find: ‘/var/lib/sss/secrets’: Permission denied
find: ‘/var/lib/sss/keytabs’: Permission denied
find: ‘/var/lib/mlocate’: Permission denied
find: ‘/var/lib/nvidia’: Permission denied
find: ‘/var/lib/mysql’: Permission denied
find: ‘/var/lib/mysql-files’: Permission denied
find: ‘/var/lib/mysql-keyring’: Permission denied
find: ‘/var/log/audit’: Permission denied
find: ‘/var/log/samba’: Permission denied
find: ‘/var/log/ppp’: Permission denied
find: ‘/var/log/pluto/peer’: Permission denied
find: ‘/var/log/speech-dispatcher’: Permission denied
find: ‘/var/log/libvirt’: Permission denied
find: ‘/var/log/gdm’: Permission denied
find: ‘/var/log/sssd’: Permission denied
find: ‘/var/cache/ldconfig’: Permission denied
find: ‘/var/cache/libvirt’: Permission denied
find: ‘/var/cache/cups’: Permission denied
find: ‘/var/db/sudo’: Permission denied
find: ‘/var/empty/sshd’: Permission denied
find: ‘/var/spool/cron’: Permission denied
find: ‘/var/spool/postfix/active’: Permission denied
find: ‘/var/spool/postfix/bounce’: Permission denied
find: ‘/var/spool/postfix/corrupt’: Permission denied
find: ‘/var/spool/postfix/defer’: Permission denied
find: ‘/var/spool/postfix/deferred’: Permission denied
find: ‘/var/spool/postfix/flush’: Permission denied
find: ‘/var/spool/postfix/hold’: Permission denied
find: ‘/var/spool/postfix/incoming’: Permission denied
find: ‘/var/spool/postfix/maildrop’: Permission denied

**Comment by strubell** [comment]
My guess is that the DATA_DIR variable isn't getting set (causing find to
be called on the filesystem root directory). Try printing the variable with
echo after setting it to make sure it worked.

My instructions are for bash and may need to be modified for different
shells.

**Comment by Surojit88** [comment]
Thanks for the prompt response Emma! Indeed that's the problem. I am trying to run this on Ubuntu and the problem has been resolved, thanks for the inputs! Am running into new problems though, will try to get them.

Thank you so much again! Means a lot :)

**Comment by strubell** [comment]
Great, glad it worked!
