### ISSUE TITLE
int() argument must be a string, a bytes-like object or a number, not 'map'

### ISSUE THREAD

**Issue by Surojit88** [iesl/dilated-cnn-ner#24]
I get the following error first up upon running preprocess.sh as  ' ./bin/preprocess.sh conf/conll/dilated-cnn.conf':

> Processing file: /home/ss06886910/NLP/Bilstm_Dilated_CNN_NER/data//conll2003//eng.train
> python /home/ss06886910/NLP/Bilstm_Dilated_CNN_NER/src/tsv_to_tfrecords.py --in_file /home/ss06886910/NLP/Bilstm_Dilated_CNN_NER/data//conll2003//eng.train --out_dir /home/ss06886910/NLP/Bilstm_Dilated_CNN_NER/data/conll2003-w3-lample/eng.train --window_size 3 --update_maps True --dataset conll2003 --update_vocab /home/ss06886910/NLP/Bilstm_Dilated_CNN_NER/data/vocabs/conll2003_cutoff_4.txt --vocab /home/ss06886910/NLP/Bilstm_Dilated_CNN_NER/data/embeddings/lample-embeddings-pre.txt
> /opt/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
>   from ._conv import register_converters as _register_converters
> Traceback (most recent call last):
>   File "/home/ss06886910/NLP/Bilstm_Dilated_CNN_NER/src/tsv_to_tfrecords.py", line 498, in <module>
>     tf.app.run()
>   File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
>     _sys.exit(main(argv))
>   File "/home/ss06886910/NLP/Bilstm_Dilated_CNN_NER/src/tsv_to_tfrecords.py", line 494, in main
>     tsv_to_examples()
>   File "/home/ss06886910/NLP/Bilstm_Dilated_CNN_NER/src/tsv_to_tfrecords.py", line 392, in tsv_to_examples
>     toks, oov, sent = make_example(writer, line_buf, label_map, token_map, shape_map, char_map, update_vocab, update_chars)
>   File "/home/ss06886910/NLP/Bilstm_Dilated_CNN_NER/src/tsv_to_tfrecords.py", line 237, in make_example
>     intmapped_labels[pad_width:pad_width+len(labels)] = map(lambda s: label_map[s], labels)
> **TypeError: int() argument must be a string, a bytes-like object or a number, not 'map'**

This is again followed by this:

> Processing file: /home/ss06886910/NLP/Bilstm_Dilated_CNN_NER/data//conll2003//eng.testa
> python /home/ss06886910/NLP/Bilstm_Dilated_CNN_NER/src/tsv_to_tfrecords.py --in_file /home/ss06886910/NLP/Bilstm_Dilated_CNN_NER/data//conll2003//eng.testa --out_dir /home/ss06886910/NLP/Bilstm_Dilated_CNN_NER/data/conll2003-w3-lample/eng.testa --window_size 3 --update_maps False --dataset conll2003 --update_vocab /home/ss06886910/NLP/Bilstm_Dilated_CNN_NER/data/vocabs/conll2003_cutoff_4.txt --vocab /home/ss06886910/NLP/Bilstm_Dilated_CNN_NER/data/embeddings/lample-embeddings-pre.txt --labels /home/ss06886910/NLP/Bilstm_Dilated_CNN_NER/data/conll2003-w3-lample/eng.train/label.txt --shapes /home/ss06886910/NLP/Bilstm_Dilated_CNN_NER/data/conll2003-w3-lample/eng.train/shape.txt --chars /home/ss06886910/NLP/Bilstm_Dilated_CNN_NER/data/conll2003-w3-lample/eng.train/char.txt
> /opt/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
>   from ._conv import register_converters as _register_converters
> Traceback (most recent call last):
>   File "/home/ss06886910/NLP/Bilstm_Dilated_CNN_NER/src/tsv_to_tfrecords.py", line 498, in <module>
>     tf.app.run()
>   File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
>     _sys.exit(main(argv))
>   File "/home/ss06886910/NLP/Bilstm_Dilated_CNN_NER/src/tsv_to_tfrecords.py", line 494, in main
>     tsv_to_examples()
>   File "/home/ss06886910/NLP/Bilstm_Dilated_CNN_NER/src/tsv_to_tfrecords.py", line 330, in tsv_to_examples
>     with open(FLAGS.labels, 'r') as f:
> FileNotFoundError: [Errno 2] **No such file or directory:** '/home/ss06886910/NLP/Bilstm_Dilated_CNN_NER/data/conll2003-w3-lample/eng.train/label.txt'

Am guessing if it is unable to create the file:
'Bilstm_Dilated_CNN_NER/data/conll2003-w3-lample/eng.train/label.txt'

;due to the initial TypeError up top.

Version info:

```
print(tf.__version__)
!python -V
```

> 1.10.1
> Python 3.6.5 :: Anaconda, Inc.

Can you help here Ms. @strubell, please?

Regards

**Comment by strubell** [comment]
try using python 2.7

**Comment by marc88** [comment]
Thanks!
