### ISSUE TITLE
About the paper

### ISSUE THREAD

**Issue by marc88** [iesl/dilated-cnn-ner#25]
Hello,

Is there any suggested reading that you'd recommend to understand your paper. I tried working through the architecture but, while using the expression for the final Dilation layer of the block, I found some points of confusion.
Please suggest further if any additional information is required.
Any help will be much appreciated.

Regards

**Comment by strubell** [comment]
is there something more specific that you're struggling with? is there a specific equation?

**Comment by Surojit88** [comment]
Hello Emma,

The figure shows notations used to derive the layers as given in the paper.

I have some confusion in the last dilation-1 layer's notation. Hope this image below is suggestive enough. Please feel free to if any more information is required.

![image](https://user-images.githubusercontent.com/42137058/49851762-20e6f300-fe08-11e8-862f-538a81eeaffe.png)

Thanks

Regards
Surojit

**Comment by marc88** [comment]
Hello Emma,

The figure shows notations used to derive the layers as given in the paper.

I have some confusion in the last dilation-1 layer's notation. Hope this image below is suggestive enough. Please feel free if any more information is required.

![image](https://user-images.githubusercontent.com/42137058/49851762-20e6f300-fe08-11e8-862f-538a81eeaffe.png)

Thanks

Regards
Surojit

**Comment by strubell** [comment]
This figure still doesn't clarify the issue for me -- is there a concrete
part that you don't understand about the last dilation-1 layer? like all
the other layers it takes the previous layer as input.

**Comment by marc88** [comment]
Ok!
Please forget everything else and just suggest if the layers upto c(5) have been formulated properly in the image above? :)
I am confused about the notations but, it won’t matter if the layers I’ve formulated are done correctly.

I do understand that every block has exponentially increasing dilation layers followed by a dilation 1 layer and we can have multiple suck blocks :)

**Comment by strubell** [comment]
it looks good to me

**Comment by marc88** [comment]
Thank you so much! :)
