### ISSUE TITLE
Any pytorch version of dilated-cnn-ner around ?

### ISSUE THREAD

**Issue by WaNePr** [iesl/dilated-cnn-ner#32]
Like mentioned in question, I would like to ask if there is any pytorch version of this work ?

**Comment by strubell** [comment]
Not that I know of, though it's certainly possible. It would be pretty easy
to implement since pytorch also has dilated convolutions.

**Comment by shira-g** [comment]
> Like mentioned in question, I would like to ask if there is any pytorch version of this work ?

https://github.com/NervanaSystems/nlp-architect/tree/improve_idcnn

(https://github.com/NervanaSystems/nlp-architect/blob/improve_idcnn/nlp_architect/nn/torch/modules/embedders.py#L147)

**Comment by strubell** [comment]
Thanks @shira-g!
