### ISSUE TITLE
How to run model with character embeddings?

### ISSUE THREAD

**Issue by egrcc** [iesl/dilated-cnn-ner#4]
Hi, 
according to Table 1 of your paper, "No models use character embeddings or lexicons. " The character embeddings is very useful for sequence labeling as stated by (G Lample - ‎2016) and (X Ma - ‎2016). I also found that your code has already implemented it (bilstm_char.py and cnn_char.py), so I modified the [L13~L15 of global.conf](https://github.com/iesl/dilated-cnn-ner/blob/e02ac0e53e80c5055bd7e3b41a271c1a108b4949/conf/global.conf#L13) to run model with character embeddings:
```
export char_dim=30
export char_tok_dim=30
export char_model="cnn"
```
Then, I ran the following steps (for ID-CNN-CRF model):
```
./bin/preprocess.sh conf/conll/dilated-cnn-viterbi.conf
./bin/train-cnn.sh conf/conll/dilated-cnn-viterbi.conf
./bin/eval-cnn.sh conf/conll/dilated-cnn-viterbi.conf --load_model /home/ljzhao/dilated-cnn-ner-master/models/dilated-cnn-viterbi.tf test
```
Is this right?

I also found that [L12 of eval-cnn.sh](https://github.com/iesl/dilated-cnn-ner/blob/e02ac0e53e80c5055bd7e3b41a271c1a108b4949/bin/eval-cnn.sh#L12) needs to be changed to the following line to correctly evaluate on the test set:
```
if [[ $4 == "test" ]]; then
```

G Lample - ‎2016: Neural Architectures for Named Entity Recognition
X Ma - ‎2016: End-to-end Sequence Labeling via Bi-directional LSTM-CNNs-CRF

**Comment by strubell** [comment]
I *think* that should be right but I can't make any guarantees right now that the implementation is correct, as I was never able to get accuracy as high as in the Lample 2016 paper. I want to get this working, though, for a different project I'm working on right now, so I will use this issue to track that. Thanks!

**Comment by egrcc** [comment]
Thanks for your reply. Is there any easy way to run this code with other datasets (e.g. POS-Tagging or Chunking)? I found the data preprocessing is too complicated to follow.

**Comment by strubell** [comment]
Sure. The easiest way to use this code to train on other tagsets would be
to create a data file with the same format as is expected for conll-2003,
except with the pos/chunk/whatever tags in the same field as this code
expects the ner tags. I think that should just work.

**Comment by egrcc** [comment]
It works. Thanks~
