### ISSUE TITLE
Replicating test score yields dev score

### ISSUE THREAD

**Issue by sbrugman** [iesl/dilated-cnn-ner#6]
Could it be that running the command to obtain the evaluation on the test set actually returns the dev score? Both commands have exactly the same output on my system, which seems rather odd.

You can find the output here:
https://github.com/sbrugman/dilated-cnn-ner/blob/master/README.md#replication-results

**Comment by sbrugman** [comment]
Problem is solved by swapping the arguments: 
  ```
  ./bin/eval-cnn.sh conf/conll/dilated-cnn.conf test --load_model path/to/model
  ```

**Comment by strubell** [comment]
Thanks for looking into this, and sorry for the fragile script!
